name: Build shaded JAR (main)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GRADLE_USER_HOME: /opt/gradle-home
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.daemon.enabled=false -Dorg.gradle.jvmargs='-Xmx2g -XX:+UseParallelGC'
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: keep using your repo script for system prep (locales, tools, cache dir)
      - name: Provision system packages + Gradle cache dir
        env:
          PREWARM_GRADLE: none
        run: |
          sudo bash scripts/setup-provisioned-runner-ubuntu24.sh

      - name: Setup Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Sanity check Java
        run: |
          which java; java -version
          which javac; javac -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Build (shadowed JAR, detekt, no tests)
        run: |
          ./gradlew --stacktrace --no-daemon build -x test

      - name: List outputs (for debugging)
        if: always()
        run: |
          echo "Contents of build/libs:"
          ls -lah build/libs || true

      - name: Upload shaded JAR artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: ClevelandCustomBlocks-${{ github.sha }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
          if-no-files-found: error

      - name: Summary
        if: always()
        run: |
          echo "## Build Artifacts" >> "$GITHUB_STEP_SUMMARY"
          if [ -d build/libs ]; then
            ls -lh build/libs >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No build/libs directory (build failed)." >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Gradle cache dir: ${GRADLE_USER_HOME}" >> "$GITHUB_STEP_SUMMARY"
