name: Generate Changelog on Tag

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

concurrency:
  group: changelog-${{ github.ref }}
  cancel-in-progress: false

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      NEW_TAG: ${{ github.ref_name }}
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      CHANGELOG_PATH: CHANGELOG.md
      INSTRUCT_PATH: instruct.txt

      LLM_BASE_URL: https://integrate.api.nvidia.com/v1
      LLM_MODEL: qwen/qwen3-coder-480b-a35b-instruct
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate/Update CHANGELOG
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          python scripts/generate_changelog.py \
            --new-tag "${NEW_TAG}" \
            --instruct "${INSTRUCT_PATH}" \
            --changelog "${CHANGELOG_PATH}" \
            --model "${LLM_MODEL}"

      - name: Push changes
        run: |
          # Only push if CHANGELOG.md actually changed
          if git diff --quiet HEAD; then
            echo "No changes to commit."
          else
            git add "${CHANGELOG_PATH}"
            git commit -m "chore(changelog): update for ${NEW_TAG}"
            git push origin "HEAD:${DEFAULT_BRANCH}"
          fi
